### ISSUE TITLE
Archive Snapp Related Code

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-services#488]
This will likely require several PRs and is aimed at achieving the complete removal of all Snapp Contract related interactions (driver, listener, models and core). In bullets this should look as follows:

- [x] Tag latest master with `snapp-stable` https://github.com/gnosis/dex-services/tree/stable-snapp
- [x] Remove all snapp related e2e-tests from `./e2e/` and Travis #491
- [x] Update docker and travis files to ignore all snapp-related builds #491
- [x] Remove `graph-listener` (not needed in stableX) - This will involve eliminating the `postgres` container and all environment variables. #491
- [x] Remove `dfusion` sub-component of `driver` #493
- [x] Move the relevant models from `dfusion-core` into `driver` #496
- [x] Remove `dfusion-core` crate entirely #496
- [x] Remove `BatchInformation` as it is no longer needed
- [x] Remove slot information from `AccountState`
- [x] Simplify logging (as we no longer need to be graph compatible)
- [x] Change `driver` to be a `bin` instead of `lib` crate
- [ ] Simplify travis build - we probably no longer need a docker-compose

Please fee free to update this list and include anything that may have been missed.

**Comment by fleupold** [comment]
The only item I see left is "Simplify logging". @nlordell, @bh2smith what exactly is left to do there?

**Comment by nlordell** [comment]
Also explore changing our CI to no longer use `docker-compose` without docker-compose.

**Comment by bh2smith** [comment]
@nlordell I believe this was completed a long time ago. Can you confirm?
